FROM python:3.12-slim

# Install sqlite-web
RUN pip install sqlite-web

# Copy your SQLite DB into the image (optional)
# COPY metadata.db /data/metadata.db
# Expose the web interface
EXPOSE 8080

# Command to run sqlite-web

CMD ["python", "-m", "sqlite_web", "--host=0.0.0.0", "--port=8080", "/data/metadata.db"]
# docker run -d -p 8080:8080 -v $(pwd)/data/metadata.db:/data/metadata.db sql-web
